### ISSUE TITLE
Handle Encrypted Keys

### ISSUE THREAD

**Issue by kameshsampath** [kameshsampath/snow-builder-collection#1]
Auto generate password and store it encrypted in a pass file/add to Snowflake config `private_key_file_pwd`

In file forgeconfig/src/security/rsa_keypair_generator.py
https://github.com/kameshsampath/snow-builder-collection/blob/e43c1e200d41e9a0156b56cd259a6ca015ac7397/forgeconfig/src/security/rsa_keypair_generator.py#L53

**Comment by KellerKev** [comment]
@kameshsampath Maybe never decrypt the key in the file system, but only in memory on the container, then generate a JWT token based on it and update the users config.toml with the token for auth
